### ISSUE TITLE
upload photos restricted from file manager

### ISSUE THREAD

**Issue by viv3kk** [andreipfeiffer/react-native-webview-android-file-upload#17]
When I try to upload photos from a specific location, the upload is disabled. I have to specifically go into gallery to select photos.
I am facing this issue in few mobiles like oneplus one (AOSP Extended 8) and nokia (8.1.0)

**Comment by viv3kk** [comment]
one phone is rooted while others are not. Facing this on nokia, samsung(tab) and oneplus(rooted)

**Comment by andreipfeiffer** [comment]
Can you also tell me the Nokia model? I know I have also tested on a Nokia, but not with Android 8.1.0
I want to make sure weather it's a Android version issue, a vendor issue, or another issue.
So far, you are the only one that reported such problems, that's why I don't want to dive into a big update yet.

**Comment by viv3kk** [comment]
yes ..i know 

> Can you also tell me the Nokia model? I know I have also tested on a Nokia, but not with Android 8.1.0
> I want to make sure weather it's a Android version issue, a vendor issue, or another issue.
> 
> So far, you are the only one that reported such problems, that's why I don't want to dive into a big update yet.

yes i know ...i will share the details in some time
