### ISSUE TITLE
<select> not working for tablets.

### ISSUE THREAD

**Issue by viv3kk** [andreipfeiffer/react-native-webview-android-file-upload#18]
select box is not working for tabs. I know this is a react native issue. Do you have any solution to this.

**Comment by andreipfeiffer** [comment]
What does "not working" means?
What is the actual behavior vs. the expected behavior?
Provide screenshots, detailed explanations. I have no idea what do you actually experience on your device.

Also, this repo tackles only `<input type="file" />`.
Handling `<select>` is really out-of-scope of this repo.
